FROM python:3.9
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt 
COPY . /app
EXPOSE 5000
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "5000"]